--创建图片表
CREATE TABLE PICTURE(
	[GUID]	CHAR(36)		NOT NULL,		--guid
	[TYPE]	INT				NOT NULL,		--类型
	URL		NVARCHAR(200)	NOT NULL,		--图片地址
	DATA	IMAGE
)
--添加主键
GO
ALTER TABLE PICTURE
     ADD CONSTRAINT PK_PICTURE PRIMARY KEY ([GUID])


--创建演员表
GO
CREATE TABLE ACTRESS(
	[GUID]			CHAR(36)		NOT NULL,	--guid
	NAME			NVARCHAR(100)	NOT NULL,	--名称
	NAME_FULL		NVARCHAR(100),				--全名
	PICTURE_GUID	CHAR(36)		NOT NULL,	--图片的guid
	URL				NVARCHAR(400)	NOT NULL	--演员信息地址
)
--添加主键
GO
ALTER TABLE ACTRESS
	ADD CONSTRAINT PK_ACTRESS PRIMARY KEY ([GUID])
--添加名称唯一约束
GO
ALTER TABLE ACTRESS
	ADD CONSTRAINT UQ_ACTRESS_NAME UNIQUE (NAME)
--添加外键约束
GO
ALTER TABLE ACTRESS
	ADD CONSTRAINT FK_ACTRESS_PICTURE_GUID FOREIGN KEY(PICTURE_GUID) REFERENCES PICTURE([GUID])


--创建作品表
GO
CREATE TABLE WORK(
	[GUID]				CHAR(36)		NOT NULL,	--guid
	TITLE				NVARCHAR(200)	NOT NULL,	--作品名称
	TITLE_FULL			NVARCHAR(200)	NOT NULL,	--作品具体名
	TITLE_CH			NVARCHAR(200),				--作品中文名
	CODE_FULL			VARCHAR(20)		NOT NULL,	--番号
	CODE				VARCHAR(20)		NOT NULL,	--简单番号
	[DATE]				DATE			NOT NULL,	--发行日期
	TIME_LENGTH			INT				NOT NULL,	--时长（分钟）
	COVER_FULL_GUID		CHAR(36)		NOT NULL,	--封面大图guid
	COVER_GUID			CHAR(36)		NOT NULL,	--封面图guid
	URL					NVARCHAR(400)	NOT NULL,	--作品页面地址
	PAGE_TYPE			INT				NOT NULL,	--作品页面类型
	ACTRESS_TYPE		INT				NOT NULL	--作品演员类型
)
--添加主键
GO
ALTER TABLE WORK
	ADD CONSTRAINT PK_WORK PRIMARY KEY ([GUID])
--添加名称唯一约束
GO
ALTER TABLE WORK
	ADD CONSTRAINT UQ_WORK_TITLE UNIQUE (TITLE)
--添加番号唯一约束
GO
ALTER TABLE WORK		
	ADD CONSTRAINT UQ_WORK_CODE_FULL UNIQUE (CODE_FULL)
--添加封面大图外键约束
GO
ALTER TABLE WORK
	ADD CONSTRAINT FK_WORK_COVER_FULL_GUID FOREIGN KEY(COVER_FULL_GUID) REFERENCES PICTURE([GUID])
--添加封面小图外键约束
GO
ALTER TABLE WORK
	ADD CONSTRAINT FK_WORK_COVER_COVER_GUID FOREIGN KEY(COVER_GUID) REFERENCES PICTURE([GUID])
--添加页面类型索引
GO
CREATE INDEX INDEX_WORK_PAGE_TYPE ON WORK(PAGE_TYPE)
--添加演员类型索引
GO
CREATE INDEX INDEX_WORK_ACTRESS_TYPE ON WORK(ACTRESS_TYPE)
	

--添加作品预览图片表
GO
CREATE TABLE WORK_PREVIEW(
	WORK_GUID		CHAR(36)		NOT NULL,	--作品guid
	PICTURE_GUID	CHAR(36)		NOT NULL	--图片guid
)
--添加主键
GO
ALTER TABLE WORK_PREVIEW
	ADD CONSTRAINT PK_WORK_PREVIEW PRIMARY KEY (WORK_GUID, PICTURE_GUID)
--添加作品guid外键约束
GO
ALTER TABLE WORK_PREVIEW
	ADD CONSTRAINT FK_WORK_PREVIEW_WORK_GUID FOREIGN KEY(WORK_GUID) REFERENCES WORK([GUID])
--添加图片guid外键约束
GO
ALTER TABLE WORK_PREVIEW	
	ADD CONSTRAINT FK_WORK_PREVIEW_PICTURE_GUID FOREIGN KEY(PICTURE_GUID) REFERENCES PICTURE([GUID])


--创建作品演员表
GO
CREATE TABLE WORK_ACTRESS(
	WORK_GUID		CHAR(36)		NOT NULL,
	ACTRESS_GUID	CHAR(36)		NOT NULL
)
--添加主键
GO
ALTER TABLE WORK_ACTRESS
	ADD CONSTRAINT PK_WORK_ACTRESS PRIMARY KEY (WORK_GUID, ACTRESS_GUID)
--添加作品guid外键约束
GO
ALTER TABLE WORK_ACTRESS
	ADD CONSTRAINT FK_WORK_ACTRESS_WORK_GUID FOREIGN KEY(WORK_GUID) REFERENCES WORK([GUID])
--添加演员guid外键约束
GO
ALTER TABLE WORK_ACTRESS	
	ADD CONSTRAINT FK_WORK_ACTRESS_ACTRESSE_GUID FOREIGN KEY(ACTRESS_GUID) REFERENCES ACTRESS([GUID])

	

--添加作品番号表
GO
CREATE TABLE WORK_DISTINCT(
	CODE			VARCHAR(20)			NOT NULL,	--番号
	TITLE			NVARCHAR(200)		NOT NULL,	--标题
	[DATE]			DATE				NOT NULL,	--发行日期
	ACTRESS_TYPE	INT					NOT NULL,	--作品演员类型
	LOCK			INT					NOT NULL,	--是否在处理中
)
--添加主键
GO
ALTER TABLE WORK_DISTINCT
	ADD CONSTRAINT PK_WORK_DISTINCT PRIMARY KEY (CODE)


--添加种子表
GO
CREATE TABLE TORRENT(
	TITLE			NVARCHAR(50)		NOT NULL,	--种子标题
	DETAIL			NVARCHAR(400)		NOT NULL,	--种子详细信息
	[HASH]			VARCHAR(50)			NOT NULL,	--哈希值
	FILE_COUNT		INT					NOT NULL,	--指向的文件个数
	FILE_SIZE		VARCHAR(10)			NOT NULL,	--指向的文件大小
	[DATE]			DATE				NOT NULL,	--日期
	[TYPE]			INT					NOT NULL,	--类型
	WORK_CODE		VARCHAR(20)			NOT NULL	--关联番号
)
--添加番号外键
GO
ALTER TABLE TORRENT	
	ADD CONSTRAINT FK_TORRENT_WORK_CODE FOREIGN KEY(WORK_CODE) REFERENCES WORK_DISTINCT(CODE)
