--创建演员表
CREATE TABLE ACTRESS(
	NAME			NVARCHAR(30)	NOT NULL,	--姓名
	NAME_FULL		NVARCHAR(100)	NOT NULL,	--显示的姓名
	URL				NVARCHAR(400)	NOT NULL	--页面地址
)
--添加姓名主键
GO
ALTER TABLE ACTRESS
	ADD CONSTRAINT PK_ACTRESS PRIMARY KEY (NAME)
	



--创建演员图片表
GO
CREATE TABLE ACTRESS_PICTURE(
	[GUID]			CHAR(36)		NOT NULL,	--GUID
	ACTRESS_NAME	NVARCHAR(30)	NOT NULL,	--演员姓名
	URL				NVARCHAR(400)	NOT NULL,	--地址
	DATA			IMAGE						--数据
)
--添加GUID主键
GO
ALTER TABLE ACTRESS_PICTURE
	ADD CONSTRAINT PK_ACTRESS_PICTURE PRIMARY KEY (GUID)
--添加演员姓名外键引用
GO
ALTER TABLE ACTRESS_PICTURE
	ADD CONSTRAINT FK_ACTRESS_PICTURE_ACTRESS_NAME 
		FOREIGN KEY (ACTRESS_NAME) REFERENCES ACTRESS(NAME)


		

--创建作品表
GO
CREATE TABLE WORK(
	CODE				VARCHAR(20)		NOT NULL,	--番号
	CODE_SIMPLE			VARCHAR(20)		NOT NULL,	--简单番号
	TITLE				NVARCHAR(200)	NOT NULL,	--标题
	TITLE_CH			NVARCHAR(200),				--中文标题
	[DATE]				DATE			NOT NULL,	--发行日期
	TIME_LENGTH			INT				NOT NULL,	--时长（分钟）
	ACTRESS_TYPE		INT				NOT NULL,	--演员类型
	URL					NVARCHAR(400)	NOT NULL	--页面地址
)
--添加番号主键
GO
ALTER TABLE WORK
	ADD CONSTRAINT PK_WORK PRIMARY KEY (CODE)
--添加标题唯一约束
GO
ALTER TABLE WORK
	ADD CONSTRAINT UQ_WORK_TITLE UNIQUE (TITLE)



--创建作品图片表
GO
CREATE TABLE WORK_PICTURE(
	[GUID]			CHAR(36)		NOT NULL,	--GUID
	WORK_CODE		VARCHAR(20)		NOT NULL,	--作品番号
	[TYPE]			INT				NOT NULL,	--图片类型类型
	URL				NVARCHAR(400)	NOT NULL,	--地址
	DATA			IMAGE						--数据
)
--添加GUID主键
GO
ALTER TABLE WORK_PICTURE
	ADD CONSTRAINT PK_WORK_PICTURE PRIMARY KEY (GUID)
--添加作品番号外键引用
GO
ALTER TABLE WORK_PICTURE
	ADD CONSTRAINT FK_WORK_PICTURE FOREIGN KEY (WORK_CODE) REFERENCES WORK(CODE)


	


--创建作品演员表
GO
CREATE TABLE WORK_ACTRESS(
	WORK_CODE		VARCHAR(20)		NOT NULL,	--作品名称
	ACTRESS_NAME	NVARCHAR(30)	NOT NULL	--地址
)
--添加主键
GO
ALTER TABLE WORK_ACTRESS
	ADD CONSTRAINT PK_WORK_ACTRESS PRIMARY KEY (WORK_CODE, ACTRESS_NAME)
--添加作品番号外键引用
GO
ALTER TABLE WORK_ACTRESS
	ADD CONSTRAINT FK_WORK_ACTRESS_WORK_CODE 
		FOREIGN KEY(WORK_CODE) REFERENCES WORK(CODE)
--添加演员姓名外键引用
GO
ALTER TABLE WORK_ACTRESS	
	ADD CONSTRAINT FK_WORK_ACTRESS_ACTRESSE_NAME 
		FOREIGN KEY(ACTRESS_NAME) REFERENCES ACTRESS(NAME)


		
		
--创建作品番号表
GO
CREATE TABLE WORK_DISTINCT(
	CODE			VARCHAR(30)			NOT NULL,	--番号
	TITLE			NVARCHAR(200)		NOT NULL,	--标题
	[DATE]			DATE				NOT NULL,	--发行日期
	ACTRESS_TYPE	INT					NOT NULL,	--作品演员类型
	LOCK			INT					NOT NULL	--是否在处理中
)
--添加主键
GO
ALTER TABLE WORK_DISTINCT
	ADD CONSTRAINT PK_WORK_DISTINCT PRIMARY KEY (CODE)

	
	

--添加种子表
GO
CREATE TABLE TORRENT(
	WORK_CODE		VARCHAR(30)			NOT NULL,	--关联番号
	TITLE			NVARCHAR(50)		NOT NULL,	--标题
	LINK			NVARCHAR(400)		NOT NULL,	--链接
	FILE_COUNT		INT					NOT NULL,	--指向的文件个数
	FILE_SIZE		VARCHAR(10)			NOT NULL,	--指向的文件大小
	[DATE]			DATE				NOT NULL,	--创建日期
	[TYPE]			INT					NOT NULL	--类型
)
--添加番号外键
GO
ALTER TABLE TORRENT	
	ADD CONSTRAINT FK_TORRENT_WORK_CODE FOREIGN KEY(WORK_CODE) REFERENCES WORK_DISTINCT(CODE)
